### ISSUE TITLE
last_login field doesn't update

### ISSUE THREAD

**Issue by RonByRonn** [nrbnlulu/strawberry-django-auth#199]
Hi. Thank you for nice library!
Is there a way to update last_login field when the JWT is issued by tokenAuth?
At the moment, last_login field is always null despite calling tokenAuth

**Comment by nrbnlulu** [comment]
Hi!
 `last_login` is a field from django auth model it is probably occurring because that the call to `authenticate`
https://github.com/nrbnlulu/strawberry-django-auth/blob/6479a5a604ec2e5abfc5f5db5c3a3f4073ebc6eb/gqlauth/jwt/types_.py#L177
returns empty handed because we don't provide any auth backend..    

I think if would  update the user to `logged_in = True` when we call this mutation this would be solved.
